### PR TITLE
Frame EVM balances

### PR DESCRIPTION
**Pull request by dmitrylavrenov**
## Tasks
- [x] introduce the pallet to operate account data with balances
- [x] implement `Currency` and `Inspect` traits for the pallet required to be used at `pallet-evm`
- [x] set up mock to be used for tests
- [x] implement basic tests to verify logic (balances related tests from `pallet-evm` tests)

### CODE REVIEW

**Comment by dmitrylavrenov** [comment]
@MOZGIII I think it's ready for review. Will add some evm transaction related tests.

**Review by MOZGIII — APPROVED** [review]
Looks good!

Any idea of what more tests we could add here?

**Comment by dmitrylavrenov** [comment]
> Looks good!
> 
> Any idea of what more tests we could add here?

I think, it would be great generally to have all tests to check `Currency` and `Inspect` implementations as well. Should we add them in this PR?

**Comment by dmitrylavrenov** [comment]
@MOZGIII `Currency` related tests have been added.

**Review by MOZGIII — COMMENTED** [review]
What about account creation and removal (i.e. DustRemoval and hooks invocation)?

**Comment by dmitrylavrenov** [comment]
> What about account creation and removal (i.e. DustRemoval and hooks invocation)?

For account creation, are you talking about this one `deposit_creating`? If yes, then the test `currency_deposit_creating_works` has been added.

For DustRemoval, is it about mocking the interface and check usage? If yes, it should be added.

**Comment by MOZGIII** [comment]
Anything that can lead to an account being created or removed, generally, should be tested...

As for how to test the `DustRemoval` - yes, that would require a mock. But I think we also should test that the actual account was created, and the evm-system events are properly invoked in all the relevant cases. Pretty much everything that goes through the `try_mutate_exists` and can potentially cause problems if implemented incorrectly on the other end.

**Comment by dmitrylavrenov** [comment]
> Anything that can lead to an account being created or removed, generally, should be tested...
> 
> As for how to test the `DustRemoval` - yes, that would require a mock. But I think we also should test that the actual account was created, and the evm-system events are properly invoked in all the relevant cases. Pretty much everything that goes through the `try_mutate_exists` and can potentially cause problems if implemented incorrectly on the other end.

Account removing and creation is tested with 
- `evm_system_account_should_be_reaped`
- `currency_deposit_creating_works`

**Comment by dmitrylavrenov** [comment]
@MOZGIII Events checks have been added now - https://github.com/humanode-network/frontier/pull/65/commits/30d164e3545155d92bb962d78050753ecf48fd09

**Review by MOZGIII — APPROVED** [review]

**Pull request merged**
